### ISSUE TITLE
Sequelize Error: connect ECONNREFUSED 127.0.0.1:3306

### ISSUE THREAD

**Issue by doornot** [eggjs-community/eggjs-realworld-example-app#18]
docker-compose up

db容器报错正常启运行

realworld容器报错: Sequelize Error: connect ECONNREFUSED 127.0.0.1:3306

**Comment by klren0312** [comment]
具体配置

**Comment by doornot** [comment]
> 具体配置

```yml
version: '3'
services: 
  realworld:
    image: sinchang/realworld:latest
    environment:
      - NODE_ENV=production
      - EGG_SERVER_ENV=prod
      - DB_USER=wang
      - DB_DATABASE=realworld
      - DB_PASSWORD=
    depends_on:
      - db
    networks:
      - docker_realworld
    ports:
      - 7001:7001

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=realworld
      - MYSQL_USER=wang
      - MYSQL_PASSWORD=
    networks:
      - docker_realworld

volumes:
  db_data:

networks:
  docker_realworld:
    driver: bridge    
```
